services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: dbP@ssw0rD!
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  provider:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: provider
    command: >
      sh -c "python manage.py runscript import_data && python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: dbP@ssw0rD!
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    external: true
